// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3dM9XHiVcKQk4KzYktMC38LNlaiwoR0A',
    appId: '1:878599125709:web:22ef6a499397172390c784',
    messagingSenderId: '878599125709',
    projectId: 'bitesy-fa8bc',
    authDomain: 'bitesy-fa8bc.firebaseapp.com',
    storageBucket: 'bitesy-fa8bc.appspot.com',
    measurementId: 'G-XPXRFJW649',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIs0lJXzF93KtiTPpdERe2YemjkeDbJF8',
    appId: '1:878599125709:android:4e15d72b7071d3fc90c784',
    messagingSenderId: '878599125709',
    projectId: 'bitesy-fa8bc',
    storageBucket: 'bitesy-fa8bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjvq4rmuh7oJ2rd4v-_0iujnbiksl32qo',
    appId: '1:878599125709:ios:3df0dc5274d1d23690c784',
    messagingSenderId: '878599125709',
    projectId: 'bitesy-fa8bc',
    storageBucket: 'bitesy-fa8bc.appspot.com',
    iosClientId: '878599125709-g5sga0e1fe2vaqq882q3g3d9hp9bmos5.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjvq4rmuh7oJ2rd4v-_0iujnbiksl32qo',
    appId: '1:878599125709:ios:3df0dc5274d1d23690c784',
    messagingSenderId: '878599125709',
    projectId: 'bitesy-fa8bc',
    storageBucket: 'bitesy-fa8bc.appspot.com',
    iosClientId: '878599125709-g5sga0e1fe2vaqq882q3g3d9hp9bmos5.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
